#include "initialize_leds.h"
#include "delay.h"
#include "led_board.h" 
#include <ti/devices/msp/msp.h>

#define POWER_STARTUP_DELAY (16)

void InitializeGPIO(void) { 
    // reset gpioa and gpiob 
    // we write rstctl so the gpio module starts in a known state 
    GPIOA->GPRCM.RSTCTL =
        (GPIO_RSTCTL_KEY_UNLOCK_W | GPIO_RSTCTL_RESETSTKYCLR_CLR |
         GPIO_RSTCTL_RESETASSERT_ASSERT); 
    GPIOB->GPRCM.RSTCTL =
        (GPIO_RSTCTL_KEY_UNLOCK_W | GPIO_RSTCTL_RESETSTKYCLR_CLR |
         GPIO_RSTCTL_RESETASSERT_ASSERT); 

    // power on gpioa and gpiob 
    // we must enable power before using the gpio registers 
    GPIOA->GPRCM.PWREN =
        (GPIO_PWREN_KEY_UNLOCK_W | GPIO_PWREN_ENABLE_ENABLE); 
    GPIOB->GPRCM.PWREN =
        (GPIO_PWREN_KEY_UNLOCK_W | GPIO_PWREN_ENABLE_ENABLE); 

    delay_cycles(POWER_STARTUP_DELAY); // short wait for power 

    // iomux: connect each pin and set function 1 (gpio) 
    // 0x00000001 selects gpio for these pins in the iomux table 
    IOMUX->SECCFG.PINCM[LED12A_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED1A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED2A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED3A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED4A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED5A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED6A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED7A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED8A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED9A_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED10A_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED11A_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 

    IOMUX->SECCFG.PINCM[LED12B_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED1B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED2B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED3B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED4B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED5B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED6B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED7B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED8B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED9B_PINCM]  = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED10B_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 
    IOMUX->SECCFG.PINCM[LED11B_PINCM] = (IOMUX_PINCM_PC_CONNECTED | (uint32_t)0x00000001); 

    /*
     * this code was written by ai
     */
    IOMUX->SECCFG.PINCM[BUTTON_PINCM] =
        (IOMUX_PINCM_PC_CONNECTED | IOMUX_PINCM25_PF_GPIOB_DIO08 |
         IOMUX_PINCM_INENA_ENABLE | IOMUX_PINCM_PIPU_ENABLE |
         IOMUX_PINCM_PIPD_DISABLE);

    // default: all leds off 
    // leds are active-low, so high means off 
    GPIOA->DOUTSET31_0 = LED_GPIOA_MASK; 
    GPIOB->DOUTSET31_0 = LED_GPIOB_MASK; 

    // enable outputs for all led pins 
    // doeset sets only the bits we care about and avoids clobbering 
    GPIOA->DOESET31_0 = LED_GPIOA_MASK; 
    GPIOB->DOESET31_0 = LED_GPIOB_MASK; 
    GPIOB->DOECLR31_0 = BUTTON_GPIOB_BIT; 
}
